// components/expenses/ExpenseList.tsx
"use client";

import { useState, useTransition } from "react";
import { useRouter, usePathname, useSearchParams } from "next/navigation";
import { deleteExpense } from "@/actions/expenses";
import { Pencil, Trash2, RefreshCw } from "lucide-react";

interface Category {
  id: string;
  name: string;
  color: string;
}

interface Expense {
  id: string;
  title: string;
  amount: { toNumber: () => number } | number;
  date: Date;
  description: string | null;
  type: "ONE_TIME" | "RECURRING";
  isAutoGenerated: boolean;
  category: Category | null;
}

interface Props {
  expenses: Expense[];
  totalPages: number;
  currentPage: number;
  onEdit: (expense: Expense) => void;
}

function toNumber(val: number | { toNumber: () => number }): number {
  return typeof val === "number" ? val : val.toNumber();
}

export default function ExpenseList({
  expenses,
  totalPages,
  currentPage,
  onEdit,
}: Props) {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  function goToPage(page: number) {
    const params = new URLSearchParams(searchParams.toString());
    params.set("page", String(page));
    router.push(`${pathname}?${params.toString()}`);
  }

  function handleDelete(id: string) {
    if (!confirm("Delete this expense?")) return;
    setDeletingId(id);
    setError(null);

    startTransition(async () => {
      const result = await deleteExpense(id);
      if (result?.error) setError(result.error);
      setDeletingId(null);
    });
  }

  if (expenses.length === 0) {
    return (
      <div
        className="bg-white dark:bg-neutral-800 rounded-xl border 
                      border-gray-200 dark:border-neutral-700 p-12 text-center"
      >
        <p className="text-4xl mb-3">🧾</p>
        <p className="text-gray-500 dark:text-gray-400 text-sm">
          No expenses found. Add your first one!
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {error && (
        <div
          className="bg-red-50 dark:bg-red-900/20 text-red-600 
                        dark:text-red-400 text-sm p-3 rounded-lg"
        >
          {error}
        </div>
      )}

      {/* Table */}
      <div
        className="bg-white dark:bg-neutral-800 rounded-xl border 
                      border-gray-200 dark:border-neutral-700 overflow-hidden"
      >
        <table className="w-full text-sm">
          <thead>
            <tr
              className="border-b border-gray-200 dark:border-neutral-700 
                           bg-gray-50 dark:bg-neutral-700/50"
            >
              <th
                className="text-left px-4 py-3 font-medium text-gray-600 
                             dark:text-gray-400"
              >
                Date
              </th>
              <th
                className="text-left px-4 py-3 font-medium text-gray-600 
                             dark:text-gray-400"
              >
                Title
              </th>
              <th
                className="text-left px-4 py-3 font-medium text-gray-600 
                             dark:text-gray-400 hidden md:table-cell"
              >
                Category
              </th>
              <th
                className="text-right px-4 py-3 font-medium text-gray-600 
                             dark:text-gray-400"
              >
                Amount
              </th>
              <th className="px-4 py-3" />
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100 dark:divide-neutral-700">
            {expenses.map((expense) => (
              <tr
                key={expense.id}
                className="hover:bg-gray-50 dark:hover:bg-neutral-700/30 transition"
              >
                <td
                  className="px-4 py-3 text-gray-500 dark:text-gray-400 
                               whitespace-nowrap"
                >
                  {new Date(expense.date).toLocaleDateString("en-IN", {
                    day: "numeric",
                    month: "short",
                    year: "numeric",
                  })}
                </td>
                <td className="px-4 py-3">
                  <div className="flex items-center gap-2">
                    <span className="text-gray-900 dark:text-white font-medium">
                      {expense.title}
                    </span>
                    {/* Badge for recurring or auto-generated */}
                    {expense.type === "RECURRING" &&
                      !expense.isAutoGenerated && (
                        <span
                          className="inline-flex items-center gap-1 text-xs 
                                       bg-purple-100 dark:bg-purple-900/30 
                                       text-purple-700 dark:text-purple-400 
                                       px-2 py-0.5 rounded-full"
                        >
                          <RefreshCw size={10} />
                          Recurring
                        </span>
                      )}
                    {expense.isAutoGenerated && (
                      <span
                        className="text-xs bg-gray-100 dark:bg-neutral-700 
                                       text-gray-500 dark:text-gray-400 
                                       px-2 py-0.5 rounded-full"
                      >
                        Auto
                      </span>
                    )}
                  </div>
                  {expense.description && (
                    <p className="text-xs text-gray-400 mt-0.5 truncate max-w-48">
                      {expense.description}
                    </p>
                  )}
                </td>
                <td className="px-4 py-3 hidden md:table-cell">
                  {expense.category ? (
                    <span
                      className="inline-flex items-center gap-1.5 text-xs 
                                     font-medium px-2.5 py-1 rounded-full"
                      style={{
                        backgroundColor: expense.category.color + "20",
                        color: expense.category.color,
                      }}
                    >
                      <span
                        className="w-1.5 h-1.5 rounded-full"
                        style={{ backgroundColor: expense.category.color }}
                      />
                      {expense.category.name}
                    </span>
                  ) : (
                    <span className="text-gray-400 text-xs">Uncategorized</span>
                  )}
                </td>
                <td
                  className="px-4 py-3 text-right font-semibold 
                               text-gray-900 dark:text-white whitespace-nowrap"
                >
                  ₹
                  {toNumber(expense.amount).toLocaleString("en-IN", {
                    minimumFractionDigits: 2,
                  })}
                </td>
                <td className="px-4 py-3">
                  <div className="flex items-center justify-end gap-1">
                    <button
                      onClick={() => onEdit(expense)}
                      className="p-1.5 text-gray-400 hover:text-blue-600 
                                 hover:bg-blue-50 dark:hover:bg-blue-900/20 
                                 rounded-lg transition"
                    >
                      <Pencil size={14} />
                    </button>
                    <button
                      onClick={() => handleDelete(expense.id)}
                      disabled={isPending && deletingId === expense.id}
                      className="p-1.5 text-gray-400 hover:text-red-600 
                                 hover:bg-red-50 dark:hover:bg-red-900/20 
                                 rounded-lg transition disabled:opacity-40"
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-between px-1">
          <p className="text-sm text-gray-500 dark:text-gray-400">
            Page {currentPage} of {totalPages}
          </p>
          <div className="flex gap-2">
            <button
              onClick={() => goToPage(currentPage - 1)}
              disabled={currentPage <= 1}
              className="px-3 py-1.5 text-sm border border-gray-300 
                         dark:border-neutral-600 rounded-lg disabled:opacity-40 
                         hover:bg-gray-50 dark:hover:bg-neutral-700 transition"
            >
              Previous
            </button>
            <button
              onClick={() => goToPage(currentPage + 1)}
              disabled={currentPage >= totalPages}
              className="px-3 py-1.5 text-sm border border-gray-300 
                         dark:border-neutral-600 rounded-lg disabled:opacity-40 
                         hover:bg-gray-50 dark:hover:bg-neutral-700 transition"
            >
              Next
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
