// app/api/cron/recurring/route.ts
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

// Vercel calls this endpoint on schedule
// We protect it with a secret so only Vercel can trigger it
export async function GET(request: Request) {
  // Security check — reject requests without the secret
  const authHeader = request.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const today = new Date();
  today.setHours(0, 0, 0, 0); // normalize to midnight

  try {
    // Get all active recurring expenses across ALL users
    const recurringExpenses = await prisma.expense.findMany({
      where: {
        type: "RECURRING",
        parentExpenseId: null, // only parents
        deletedAt: null,
        recurringStartDate: { lte: today }, // started on or before today
        OR: [
          { recurringEndDate: null }, // no end date set
          { recurringEndDate: { gte: today } }, // end date is today or future
        ],
      },
    });

    let generated = 0;
    let skipped = 0;

    for (const expense of recurringExpenses) {
      const shouldGenerate = checkShouldGenerate(
        expense.recurringFrequency!,
        expense.recurringStartDate!,
        today
      );

      if (!shouldGenerate) {
        skipped++;
        continue;
      }

      // Idempotency check — did we already generate for today?
      // This is what prevents duplicates if cron runs twice
      const alreadyGenerated = await prisma.expense.findFirst({
        where: {
          parentExpenseId: expense.id,
          date: today,
          isAutoGenerated: true,
        },
      });

      if (alreadyGenerated) {
        skipped++;
        continue;
      }

      // Create the child entry
      await prisma.expense.create({
        data: {
          userId: expense.userId,
          title: expense.title,
          amount: expense.amount,
          date: today,
          type: "ONE_TIME", // child entries are one-time
          categoryId: expense.categoryId,
          description: expense.description,
          parentExpenseId: expense.id, // link to parent
          isAutoGenerated: true, // flag so UI can show "Auto" badge
        },
      });

      generated++;
    }

    return NextResponse.json({
      success: true,
      generated,
      skipped,
      total: recurringExpenses.length,
    });
  } catch (error) {
    console.error("Cron job failed:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

// ─── Helper: should we generate an entry today? ───────────────────────────────
function checkShouldGenerate(
  frequency: string,
  startDate: Date,
  today: Date
): boolean {
  switch (frequency) {
    case "DAILY":
      // Every day — always true if we passed the date checks above
      return true;

    case "WEEKLY":
      // Same day of week as the start date
      return today.getDay() === startDate.getDay();

    case "MONTHLY":
      // Same day of month as the start date
      // Edge case: if start was 31st and month has 28 days,
      // we use last day of month
      const lastDayOfMonth = new Date(
        today.getFullYear(),
        today.getMonth() + 1,
        0
      ).getDate();

      const targetDay = Math.min(startDate.getDate(), lastDayOfMonth);
      return today.getDate() === targetDay;

    case "YEARLY":
      // Same month AND day as the start date
      return (
        today.getMonth() === startDate.getMonth() &&
        today.getDate() === startDate.getDate()
      );

    default:
      return false;
  }
}
